apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  selector:
    matchLabels:
      app: syntax
  replicas: 2
  template:
    metadata:
      labels:
        app: syntax
    spec:
      containers:
        - name: flipkart
          image: 975049945075.dkr.ecr.us-east-1.amazonaws.com/ekart:1.4-2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070


---

apiVersion: v1 
kind: Service
metadata:
  name: flipkart-services
spec:
  selector:
    app: syntax
  ports:
    - protocol: "TCP"
      port: 8070 
      targetPort: 8070 
  type: LoadBalancer
